apiVersion: apps/v1
kind: Deployment
metadata:
  name: codebox
  labels:
    app: codebox
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: codebox
  template:
    metadata:
      labels:
        app: codebox
    spec:
      containers:
        - name: codebox
          image: codebox:dev
          env:
            - name: PGSQL_ENV
              valueFrom:
                configMapKeyRef:
                  name: codebox-configmap

            - name: PGSQL_PASS
              valueFrom:
                configMapKeyRef:
                  name: codebox-configmap

          ports:
            - containerPort: 4000

---

apiVersion: v1
kind: Service
metadata:
  name: codebox-service
spec:
  type: NodePort
  selector:
    app: codebox
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000