apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: pgsql
    template:
      metadata:
        labels:
          app: pgsql
      spec:
        containers:
          - name: postgres
            image: postgres:14.2
            ports:
              - containerPort: 5432
            env:
              - name: POSTGRESQL_ENV
                  valueFrom:
                  configMapKeyRef:
                    name: pgsql-configmap

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000