version: '3.8'

services:
    codebox:
      image: codebox:dev
      environment:
         PGUSER: codebox_user
         PGPASSWORD: QWEqwe123
         PGDATABASE: codebox_dev
         PGPORT: 5432
         PGHOST: db
      ports:
         - '4000:4000'
      depends_on:
         - db
    db:
      image: postgres:14-alpine
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=QWEqwe123
        - POSTGRES_DB=postgres
      ports:
        - 5432:5432
      volumes:
        - ./init.sh:/docker-entrypoint-initdb.d/init-user-db.sh
